### ISSUE TITLE
I'm encountering installation issues on the Windows system that seem to be related to CUDA. I can confirm that CUDA has been installed in my virtual environment. Is there a specific version requirement for CUDA?

### ISSUE THREAD

**Issue by tianxianli564** [Adamdad/rational_kat_cu#3]
I'm encountering installation issues on the Windows system that seem to be related to CUDA. I can confirm that CUDA has been installed in my virtual environment. Is there a specific version requirement for CUDA?
Obtaining file:///C:/Windows/System32/rational_kat_cu
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Windows\System32\rational_kat_cu\setup.py", line 19, in <module>
          CUDAExtension(name='kat_rational_cu',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\admin\anaconda3\envs\pytorch\Lib\site-packages\torch\utils\cpp_extension.py", line 1076, in CUDAExtension
          library_dirs += library_paths(cuda=True)
                          ^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\admin\anaconda3\envs\pytorch\Lib\site-packages\torch\utils\cpp_extension.py", line 1214, in library_paths
          paths.append(_join_cuda_home(lib_dir))
                       ^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\admin\anaconda3\envs\pytorch\Lib\site-packages\torch\utils\cpp_extension.py", line 2416, in _join_cuda_home
          raise OSError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by janicet999** [comment]
I have the same question , have you solved it？
